const ADD_TODO = 'ADD_TODO'
const TOGGLE_TODO = 'TOGGLE_TODO'
const SET_FILTER = 'SET_FILTER'
const SET_TODO_TEXT = 'SET_TODO_TEXT'
const TODO_FETCH_REQUEST = 'TODO_FETCH_REQUEST'
const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS'
const TODO_FETCH_FAILURE = 'TODO_FETCH_FAILURE'

export default { ADD_TODO, TOGGLE_TODO, SET_FILTER, SET_TODO_TEXT, TODO_FETCH_REQUEST, TODO_FETCH_SUCCESS, TODO_FETCH_FAILURE }